import type { Metadata } from "next";
import { Poppins, Tektur } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
  subsets: ["latin"]
});

const tektur = Tektur({
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--font-tektur",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Gym Test App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${tektur.variable} antialiased`}>{children}</body>
    </html>
  );
}
